### ISSUE TITLE
`Install-Font`: Only works when invoked as script (not via module)

### ISSUE THREAD

**Issue by God-damnit-all** [ralish/PSWinGlue#10]
I kept getting a "Unable to read font" error using `Install-Font "$pwd"`, so I thought I'd debug it. I was surprised to find, however, that it works just fine when I ran:
```
& "$profile\..\Modules\PSWinGlue\0.6.10\Scripts\Install-Font.ps1" "$pwd"
 ```
I thought maybe it was a PowerShell 7 issue, but I installed PSWinGlue on 5.1 and it exhibits the same behavior there as well.

I made sure I was using version `0.6.10` of PSWinGlue in both cases.

Conversely, Get-Fonts and Uninstall-Font both work just fine without having to invoke the script file by path.

**Comment by God-damnit-all** [comment]
I think it might be related to $global:PSWinGluePackageCounter, but I can't be certain.

**Comment by God-damnit-all** [comment]
Okay, well, `$global:PSWinGluePackageCounter` IS an issue. Apparently when you try to increment a global variable from a module scope it has to actually exist first.

This fixes that issue:
```
    try {
        [void](Get-Variable PSWinGluePackageCounter -Scope Global -ErrorAction Stop)
    } catch {
        New-Variable PSWinGluePackageCounter -Scope Global
    }
```
But unfortunately, while this code does make the $global:PSWinGluePackageCounter variable work correctly, this doesn't fix the issue of it being unable to read the font.

**Comment by God-damnit-all** [comment]
Yeah, there's some serious scope shenanigans going on here that is proving a pain in the ass to untangle, apparently `$PartCounter` is a problem too. I'm giving up on it but I'm 99% certain that the module scope is really messing you up here.

**Comment by ralish** [comment]
Thanks for reporting this! I've pushed a fix, plus squashed a few other bugs I found in the font scripts, and have released v0.6.11. I tested the `Install-Font` script for correctness on a Windows 11 24H2 VM as well, and everything now looks good. You were also correct by the way; it absolutely was due to `PSWinGluePackageCounter`. Nice work tracking that down.

**Comment by God-damnit-all** [comment]
> Thanks for reporting this! I've pushed a fix, plus squashed a few other bugs I found in the font scripts, and have released v0.6.11. I tested the `Install-Font` script for correctness on a Windows 11 24H2 VM as well, and everything now looks good. You were also correct by the way; it absolutely was due to `PSWinGluePackageCounter`. Nice work tracking that down.

I'm not sure if the way you did it actually works though. I used the New-Variable function for a reason, in my testing it was the only way to get the variable on the ACTUAL global scope. When I input `$global:PSWinGluePackageCounter` after I run Install-Font, nothing returns, and as I understand, that's a problem that's going to lead to non-unique IDs.

**Comment by God-damnit-all** [comment]
Granted, it doesn't error anymore, but it's probably not keeping proper track of the counter. I can't say for sure though.

**Comment by ralish** [comment]
I checked this when testing and it all seemed fine? Incidentally, you can use the `-WhatIf` switch on `Install-Font` to test, as it has to run the affected code to determine the correct font name. On PowerShell v7.4.6 running from the module via implicit import:

```
 ~#@❯ Install-Font -Path .\CodeNewRoman\CodeNewRomanNerdFont-Bold.otf -Scope User -Method Manual -Verbose -WhatIf
What if: Performing the operation "New Item" on target "Item: HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts".
What if: Performing the operation "Install font manually" on target "CodeNewRomanNerdFont-Bold.otf".
 ~#@❯ $global:PSWinGluePackageCounter
1
 ~#@❯ Install-Font -Path .\CodeNewRoman\CodeNewRomanNerdFont-Bold.otf -Scope User -Method Manual -Verbose -WhatIf
What if: Performing the operation "New Item" on target "Item: HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts".
What if: Performing the operation "Install font manually" on target "CodeNewRomanNerdFont-Bold.otf".
 ~#@❯ $global:PSWinGluePackageCounter
2
 ~#@❯ Install-Font -Path .\CodeNewRoman\CodeNewRomanNerdFont-Bold.otf -Scope User -Method Manual -Verbose -WhatIf
What if: Performing the operation "New Item" on target "Item: HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts".
What if: Performing the operation "Install font manually" on target "CodeNewRomanNerdFont-Bold.otf".
 ~#@❯ $global:PSWinGluePackageCounter
3
```
