### ISSUE TITLE
`Install-Font`: Add support for uninstalling existing font

### ISSUE THREAD

**Issue by felipecrs** [ralish/PSWinGlue#6]
Today I realized that if I try to install font files with this script that has different file names (or maybe metadata like version), the two fonts gets installed:

1. https://github.com/ryanoasis/nerd-fonts/raw/bd93a872a6af6e90ee7a95106bce092bef495a11/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete%20Mono.ttf
2. https://github.com/ryanoasis/nerd-fonts/raw/efb10b01844fe958c4fd504735429260c09ee348/patched-fonts/FiraCode/Regular/FiraCodeNerdFontMono-Regular.ttf

https://user-images.githubusercontent.com/29582865/235370834-4649562e-9e0c-478c-9371-51f9625654a1.mp4

It would be super great if the `Install-Font` had an option like `-UninstallFirst` by the font name (like `Uninstall-Font.ps1` does) to ensure a consistent result (i.e. that the new font file I installed will be the font face used going forward).

I could simply call `Uninstall-Font.ps1` before calling `Install-Font.ps1` as well, however, it errors out when the font is not previously installed so it's a little difficult to script around it.

**Comment by ralish** [comment]
@felipecrs I should be able to take a look at this on the coming weekend.

**Comment by ralish** [comment]
Done and released in `v0.6.5`. The `Install-Font` command now has an `-UninstallExisting` parameter.

**Comment by felipecrs** [comment]
That's really awesome. I'll try it out soon!

**Comment by felipecrs** [comment]
It's apparently working well, thank you!
